// Copyright 2024 HiveVM.ORG. All rights reserved.
// Copyright (c) 2006, Sun Microsystems, Inc. All rights reserved.
// Copyright (c) 2007-2009, Paul Cager. All rights reserved.
// Copyright 2011 Google Inc. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Derived from JavaCC 7.0.12: org/javacc/parser/OutputFile.java, org/javacc/parser/ParseGen.java

package org.hivevm.source;

import org.jspecify.annotations.NonNull;

import java.io.OutputStream;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.security.DigestOutputStream;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HexFormat;
import java.util.Locale;
import java.util.stream.IntStream;

/**
 * The {@link LinePrinter} a template renders into. It wraps an output stream in a
 * {@link PrintWriter}, computes a digest (MD5) of the written contents, and ends the file with that
 * checksum.
 *
 * <p>It used to be the {@link org.hivevm.core.Environment} a template read from as well, so as to
 * record every name looked up and list them as the file's options: a trace of the template's
 * internals that changed whenever a template was reorganised. Generated files carry no options
 * line any more (ADR-0033).
 */
class TemplateWriter implements LinePrinter, AutoCloseable {

    private static final String INDENT = "    ";

    private final PrintWriter writer;
    private final DigestOutputStream stream;

    private int indent;
    private boolean newLine;

    /**
     * Constructs an instance of {@link TemplateWriter}.
     */
    private TemplateWriter(DigestOutputStream stream) {
        // UTF-8, as Template.render decodes it: the checksum is taken over these bytes.
        this.writer = new PrintWriter(stream, false, StandardCharsets.UTF_8);
        this.stream = stream;
        this.indent = 0;
        this.newLine = false;
    }

    /**
     * Creates an instance of MD5 {@link MessageDigest}.
     */
    private static MessageDigest create() {
        try {
            return MessageDigest.getInstance("MD5");
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public final void println() {
        this.newLine = true;
        writer.write('\n');
    }

    @Override
    public final void print(@NonNull String text) {
        for (var line : text.splitWithDelimiters("\n", -1)) {
            if (line.equals("\n")) {
                newLine = true;
                writer.write('\n');
            } else if (!line.isEmpty()) {
                if (newLine) {
                    IntStream.range(0, indent).forEach(i -> writer.write(TemplateWriter.INDENT));
                }
                newLine = false;
                write(line);
            }
        }
    }

    /**
     * Writes a string.  This method cannot be inherited from the Writer class
     * because it must suppress I/O exceptions.
     *
     * @param s String to be written
     */
    public final void write(@NonNull String s) {
        writer.write(s.replace("\t", TemplateWriter.INDENT));
    }

    public final TemplateWriter indent() {
        this.indent++;
        return this;
    }

    public final TemplateWriter outdent() {
        this.indent--;
        return this;
    }

    /**
     * Closes the stream and releases any system resources associated with it. Closing a previously
     * closed stream has no effect.
     */
    @Override
    public void close() {
        writer.flush();
        writer.printf("\n// Checksum=%s (Do not edit this line!)\n", HexFormat.of()
                .formatHex(this.stream.getMessageDigest().digest()).toUpperCase(Locale.ROOT));
        writer.close();
    }

    /**
     * Creates a writer into {@code stream} that starts with the banner {@code title} and ends with
     * the checksum.
     */
    public static TemplateWriter create(String title, OutputStream stream) {
        var digest = new DigestOutputStream(stream, TemplateWriter.create());
        var writer = new TemplateWriter(digest);
        writer.writer.printf("// Generated by %s - Do not edit this line!\n\n", title);
        return writer;
    }
}