// Copyright 2024 HiveVM.ORG. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
package org.hivevm.cc.jjtree;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.StringWriter;
import java.text.ParseException;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.hivevm.cc.Language;
import org.hivevm.cc.Parser;
import org.hivevm.cc.generator.GeneratorProvider;

public class JJTreeParser extends Parser {

    private static final Pattern GENERATED = Pattern.compile("@generated\\(([^)]+)\\)");

    public JJTreeParser(File file, Language language, File targetDir, List<String> customNodes) {
        super(file, language, targetDir, customNodes);
    }

    protected String parseJJTree(String filename, List<String> arguments)
            throws IOException, ParseException {
        var text = super.parseJJTree(filename, arguments);
        if (JJTreeParser.isGenerated(text)) {
            System.out.printf("%s was generated by jjtree.  Cannot run jjtree again.\n", filename);
            System.exit(1);
        }

        var options = parseContext(arguments);

        var parser = new JJTreeParserDefault(text, options);
        var grammar = parser.parse();
        if (Boolean.getBoolean("jjtree-dump")) {
            grammar.dump(" ");
        }

        var buffer = new StringWriter();
        var generator = GeneratorProvider.generatorFor(options.getOutputLanguage());
        try (var writer = new ASTWriter(buffer, options.getOutputLanguage())) {
            Parser.writeGenerated(writer);
            generator.generateAST(grammar, writer, options);
        }

        text = buffer.toString();
        System.out.println("Annotated grammar generated successfully!");

        var jj = options.getOutputFile().isEmpty()
                ? filename.substring(0, filename.length() - 1)
                : options.getOutputFile();
        Parser.createOutputDir(options.getOutputDirectory());
        try (var writer = new FileWriter(new File(options.getOutputDirectory(), jj))) {
            writer.write(text);
        }
        return text;
    }

    /**
     * Returns true if tool name passed is one of the tool names returned by
     * getToolNames(fileName).
     */
    private static boolean isGenerated(String data) {
        for (var element : JJTreeParser.readToolNameList(data)) {
            if ("JJTree".equals(element)) {
                return true;
            }
        }
        return false;
    }

    /**
     * Parses the tool list from the generated string.
     */
    private static List<String> readToolNameList(String text) {
        Matcher matcher = JJTreeParser.GENERATED.matcher(text);
        if (matcher.find())
            return Arrays.asList(matcher.group(1).split(","));
        return Collections.emptyList();
    }
}
