// Generated by HiveVM Waggle v.1.0 - Do not edit this line!

// Copyright 2024 HiveVM.ORG. All rights reserved.
// Copyright (c) 2006, Sun Microsystems, Inc. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Derived from JavaCC 7.0.12: org/javacc/jjtree/ASTOptions.java, src/main/resources/templates/MultiNode.template

package org.hivevm.waggle.grammar;

public class ASTBNFOneOrMore extends Node {

    public ASTBNFOneOrMore(Parser p, int id) {
        super(p, id);
    }

    public Object jjtAccept(NodeVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }
}
// Checksum=AFF35AEB7D4667B94FC092A57D0BCB03 (Do not edit this line!)
