// Generated by HiveVM Waggle v.1.0 - Do not edit this line!

// Copyright 2024 HiveVM.ORG. All rights reserved.
// Copyright (c) 2006, Sun Microsystems, Inc. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Derived from JavaCC 7.0.12: src/main/resources/templates/TokenManagerBoilerPlateMethods.template, src/main/resources/templates/TableDrivenTokenManager.template

package org.hivevm.waggle.grammar;

/**
 * Token Manager.
 */
class Lexer {

    static long[] jjbitVec0 = {0xfffffffffffffffeL, 0xffffffffffffffffL, 0xffffffffffffffffL, 0xffffffffffffffffL};
    static long[] jjbitVec2 = {0x0L, 0x0L, 0xffffffffffffffffL, 0xffffffffffffffffL};
    static long[] jjbitVec3 = {0x0L, 0x0L, 0xfffffffc00000000L, 0xffffffffffffffffL};

    private final int jjStopStringLiteralDfa_0(int pos, long active0) {
        switch (pos) {
            case 0:
                if ((active0 & 0x1000000000000L) != 0L)
                    return 4;
                if ((active0 & 0x1f8003feL) != 0L) {
                    jjmatchedKind = 60;
                    return 28;
                }
                return -1;
            case 1:
                if ((active0 & 0x1f8003feL) != 0L) {
                    jjmatchedKind = 60;
                    jjmatchedPos = 1;
                    return 28;
                }
                return -1;
            case 2:
                if ((active0 & 0x1000200L) != 0L)
                    return 28;
                if ((active0 & 0x1e8001feL) != 0L) {
                    jjmatchedKind = 60;
                    jjmatchedPos = 2;
                    return 28;
                }
                return -1;
            case 3:
                if ((active0 & 0xe000180L) != 0L)
                    return 28;
                if ((active0 & 0x1080007eL) != 0L) {
                    jjmatchedKind = 60;
                    jjmatchedPos = 3;
                    return 28;
                }
                return -1;
            case 4:
                if ((active0 & 0x10000020L) != 0L)
                    return 28;
                if ((active0 & 0x80005eL) != 0L) {
                    jjmatchedKind = 60;
                    jjmatchedPos = 4;
                    return 28;
                }
                return -1;
            case 5:
                if ((active0 & 0x80005eL) != 0L) {
                    jjmatchedKind = 60;
                    jjmatchedPos = 5;
                    return 28;
                }
                return -1;
            case 6:
                if ((active0 & 0x800018L) != 0L)
                    return 28;
                if ((active0 & 0x46L) != 0L) {
                    jjmatchedKind = 60;
                    jjmatchedPos = 6;
                    return 28;
                }
                return -1;
            case 7:
                if ((active0 & 0x46L) != 0L) {
                    jjmatchedKind = 60;
                    jjmatchedPos = 7;
                    return 28;
                }
                return -1;
            case 8:
                if ((active0 & 0x44L) != 0L) {
                    jjmatchedKind = 60;
                    jjmatchedPos = 8;
                    return 28;
                }
                if ((active0 & 0x2L) != 0L)
                    return 28;
                return -1;
            case 9:
                if ((active0 & 0x44L) != 0L) {
                    jjmatchedKind = 60;
                    jjmatchedPos = 9;
                    return 28;
                }
                return -1;
            case 10:
                if ((active0 & 0x4L) != 0L)
                    return 28;
                if ((active0 & 0x40L) != 0L) {
                    jjmatchedKind = 60;
                    jjmatchedPos = 10;
                    return 28;
                }
                return -1;
            case 11:
                if ((active0 & 0x40L) != 0L) {
                    jjmatchedKind = 60;
                    jjmatchedPos = 11;
                    return 28;
                }
                return -1;
            default:
                return -1;
        }
    }

    private final int jjStartNfa_0(int pos, long active0) {
        return jjMoveNfa_0(jjStopStringLiteralDfa_0(pos, active0), pos + 1);
    }

    private int jjStopAtPos(int pos, int kind) {
        jjmatchedKind = kind;
        jjmatchedPos = pos;
        return pos + 1;
    }

    private int jjMoveStringLiteralDfa0_0() {
        switch (curChar) {
            case 35: {
                return jjStopAtPos(0, 54);
            }
            case 40: {
                return jjStopAtPos(0, 40);
            }
            case 41: {
                return jjStopAtPos(0, 41);
            }
            case 42: {
                return jjStopAtPos(0, 58);
            }
            case 43: {
                return jjStopAtPos(0, 56);
            }
            case 44: {
                return jjStopAtPos(0, 46);
            }
            case 45: {
                return jjStopAtPos(0, 57);
            }
            case 46: {
                return jjStartNfaWithStates_0(0, 48, 4);
            }
            case 47: {
                return jjMoveStringLiteralDfa1_0(0x18000L);
            }
            case 58: {
                return jjStopAtPos(0, 55);
            }
            case 59: {
                return jjStopAtPos(0, 47);
            }
            case 60: {
                jjmatchedKind = 51;
                return jjMoveStringLiteralDfa1_0(0x20000L);
            }
            case 61: {
                return jjStopAtPos(0, 49);
            }
            case 62: {
                return jjStopAtPos(0, 50);
            }
            case 63: {
                return jjStopAtPos(0, 53);
            }
            case 69: {
                return jjMoveStringLiteralDfa1_0(0x200L);
            }
            case 73: {
                return jjMoveStringLiteralDfa1_0(0x4L);
            }
            case 76: {
                return jjMoveStringLiteralDfa1_0(0x2L);
            }
            case 77: {
                return jjMoveStringLiteralDfa1_0(0x80L);
            }
            case 83: {
                return jjMoveStringLiteralDfa1_0(0x140L);
            }
            case 84: {
                return jjMoveStringLiteralDfa1_0(0x20L);
            }
            case 91: {
                return jjStopAtPos(0, 44);
            }
            case 93: {
                return jjStopAtPos(0, 45);
            }
            case 98: {
                return jjMoveStringLiteralDfa1_0(0x800000L);
            }
            case 99: {
                return jjMoveStringLiteralDfa1_0(0x2000000L);
            }
            case 102: {
                return jjMoveStringLiteralDfa1_0(0x10000000L);
            }
            case 103: {
                return jjMoveStringLiteralDfa1_0(0x8L);
            }
            case 105: {
                return jjMoveStringLiteralDfa1_0(0x1000000L);
            }
            case 110: {
                return jjMoveStringLiteralDfa1_0(0x4000000L);
            }
            case 111: {
                return jjMoveStringLiteralDfa1_0(0x10L);
            }
            case 116: {
                return jjMoveStringLiteralDfa1_0(0x8000000L);
            }
            case 123: {
                return jjStopAtPos(0, 42);
            }
            case 124: {
                return jjStopAtPos(0, 59);
            }
            case 125: {
                return jjStopAtPos(0, 43);
            }
            case 126: {
                return jjStopAtPos(0, 52);
            }
            default: {
                return jjMoveNfa_0(0, 0);
            }
        }
    }

    private int jjMoveStringLiteralDfa1_0(long active0) {
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(0, active0);
            return 1;
        }
        switch (curChar) {
            case 42: {
                if ((active0 & 0x10000L) != 0L)return jjStopAtPos(1, 16);
                break;
            }
            case 47: {
                if ((active0 & 0x8000L) != 0L)return jjStopAtPos(1, 15);
                break;
            }
            case 63: {
                if ((active0 & 0x20000L) != 0L)return jjStopAtPos(1, 17);
                break;
            }
            case 71: {
                return jjMoveStringLiteralDfa2_0(active0, 0x4L);
            }
            case 75: {
                return jjMoveStringLiteralDfa2_0(active0, 0x100L);
            }
            case 79: {
                return jjMoveStringLiteralDfa2_0(active0, 0x2a2L);
            }
            case 80: {
                return jjMoveStringLiteralDfa2_0(active0, 0x40L);
            }
            case 97: {
                return jjMoveStringLiteralDfa2_0(active0, 0x10000000L);
            }
            case 104: {
                return jjMoveStringLiteralDfa2_0(active0, 0x2000000L);
            }
            case 110: {
                return jjMoveStringLiteralDfa2_0(active0, 0x1000000L);
            }
            case 111: {
                return jjMoveStringLiteralDfa2_0(active0, 0x800000L);
            }
            case 112: {
                return jjMoveStringLiteralDfa2_0(active0, 0x10L);
            }
            case 114: {
                return jjMoveStringLiteralDfa2_0(active0, 0x8000008L);
            }
            case 117: {
                return jjMoveStringLiteralDfa2_0(active0, 0x4000000L);
            }
            default: {
                break;
            }
        }
        return jjStartNfa_0(0, active0);
    }

    private int jjMoveStringLiteralDfa2_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L) {
            return jjStartNfa_0(0, old0);
        }
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(1, active0);
            return 2;
        }
        switch (curChar) {
            case 69: {
                return jjMoveStringLiteralDfa3_0(active0, 0x40L);
            }
            case 70: {
                if ((active0 & 0x200L) != 0L)return jjStartNfaWithStates_0(2, 9, 28);
                break;
            }
            case 73: {
                return jjMoveStringLiteralDfa3_0(active0, 0x100L);
            }
            case 75: {
                return jjMoveStringLiteralDfa3_0(active0, 0x20L);
            }
            case 78: {
                return jjMoveStringLiteralDfa3_0(active0, 0x4L);
            }
            case 79: {
                return jjMoveStringLiteralDfa3_0(active0, 0x2L);
            }
            case 82: {
                return jjMoveStringLiteralDfa3_0(active0, 0x80L);
            }
            case 97: {
                return jjMoveStringLiteralDfa3_0(active0, 0x2000008L);
            }
            case 108: {
                return jjMoveStringLiteralDfa3_0(active0, 0x14000000L);
            }
            case 111: {
                return jjMoveStringLiteralDfa3_0(active0, 0x800000L);
            }
            case 116: {
                if ((active0 & 0x1000000L) != 0L)return jjStartNfaWithStates_0(2, 24, 28);
                return jjMoveStringLiteralDfa3_0(active0, 0x10L);
            }
            case 117: {
                return jjMoveStringLiteralDfa3_0(active0, 0x8000000L);
            }
            default: {
                break;
            }
        }
        return jjStartNfa_0(1, active0);
    }

    private int jjMoveStringLiteralDfa3_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L) {
            return jjStartNfa_0(1, old0);
        }
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(2, active0);
            return 3;
        }
        switch (curChar) {
            case 67: {
                return jjMoveStringLiteralDfa4_0(active0, 0x40L);
            }
            case 69: {
                if ((active0 & 0x80L) != 0L)return jjStartNfaWithStates_0(3, 7, 28);
                return jjMoveStringLiteralDfa4_0(active0, 0x20L);
            }
            case 75: {
                return jjMoveStringLiteralDfa4_0(active0, 0x2L);
            }
            case 79: {
                return jjMoveStringLiteralDfa4_0(active0, 0x4L);
            }
            case 80: {
                if ((active0 & 0x100L) != 0L)return jjStartNfaWithStates_0(3, 8, 28);
                break;
            }
            case 101: {
                if ((active0 & 0x8000000L) != 0L)return jjStartNfaWithStates_0(3, 27, 28);
                break;
            }
            case 105: {
                return jjMoveStringLiteralDfa4_0(active0, 0x10L);
            }
            case 108: {
                if ((active0 & 0x4000000L) != 0L)return jjStartNfaWithStates_0(3, 26, 28);
                return jjMoveStringLiteralDfa4_0(active0, 0x800000L);
            }
            case 109: {
                return jjMoveStringLiteralDfa4_0(active0, 0x8L);
            }
            case 114: {
                if ((active0 & 0x2000000L) != 0L)return jjStartNfaWithStates_0(3, 25, 28);
                break;
            }
            case 115: {
                return jjMoveStringLiteralDfa4_0(active0, 0x10000000L);
            }
            default: {
                break;
            }
        }
        return jjStartNfa_0(2, active0);
    }

    private int jjMoveStringLiteralDfa4_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L) {
            return jjStartNfa_0(2, old0);
        }
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(3, active0);
            return 4;
        }
        switch (curChar) {
            case 65: {
                return jjMoveStringLiteralDfa5_0(active0, 0x2L);
            }
            case 73: {
                return jjMoveStringLiteralDfa5_0(active0, 0x40L);
            }
            case 78: {
                if ((active0 & 0x20L) != 0L)return jjStartNfaWithStates_0(4, 5, 28);
                break;
            }
            case 82: {
                return jjMoveStringLiteralDfa5_0(active0, 0x4L);
            }
            case 101: {
                if ((active0 & 0x10000000L) != 0L)return jjStartNfaWithStates_0(4, 28, 28);
                return jjMoveStringLiteralDfa5_0(active0, 0x800000L);
            }
            case 109: {
                return jjMoveStringLiteralDfa5_0(active0, 0x8L);
            }
            case 111: {
                return jjMoveStringLiteralDfa5_0(active0, 0x10L);
            }
            default: {
                break;
            }
        }
        return jjStartNfa_0(3, active0);
    }

    private int jjMoveStringLiteralDfa5_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L) {
            return jjStartNfa_0(3, old0);
        }
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(4, active0);
            return 5;
        }
        switch (curChar) {
            case 65: {
                return jjMoveStringLiteralDfa6_0(active0, 0x40L);
            }
            case 69: {
                return jjMoveStringLiteralDfa6_0(active0, 0x4L);
            }
            case 72: {
                return jjMoveStringLiteralDfa6_0(active0, 0x2L);
            }
            case 97: {
                return jjMoveStringLiteralDfa6_0(active0, 0x800008L);
            }
            case 110: {
                return jjMoveStringLiteralDfa6_0(active0, 0x10L);
            }
            default: {
                break;
            }
        }
        return jjStartNfa_0(4, active0);
    }

    private int jjMoveStringLiteralDfa6_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L) {
            return jjStartNfa_0(4, old0);
        }
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(5, active0);
            return 6;
        }
        switch (curChar) {
            case 69: {
                return jjMoveStringLiteralDfa7_0(active0, 0x2L);
            }
            case 76: {
                return jjMoveStringLiteralDfa7_0(active0, 0x40L);
            }
            case 95: {
                return jjMoveStringLiteralDfa7_0(active0, 0x4L);
            }
            case 110: {
                if ((active0 & 0x800000L) != 0L)return jjStartNfaWithStates_0(6, 23, 28);
                break;
            }
            case 114: {
                if ((active0 & 0x8L) != 0L)return jjStartNfaWithStates_0(6, 3, 28);
                break;
            }
            case 115: {
                if ((active0 & 0x10L) != 0L)return jjStartNfaWithStates_0(6, 4, 28);
                break;
            }
            default: {
                break;
            }
        }
        return jjStartNfa_0(5, active0);
    }

    private int jjMoveStringLiteralDfa7_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L) {
            return jjStartNfa_0(5, old0);
        }
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(6, active0);
            return 7;
        }
        switch (curChar) {
            case 65: {
                return jjMoveStringLiteralDfa8_0(active0, 0x2L);
            }
            case 67: {
                return jjMoveStringLiteralDfa8_0(active0, 0x4L);
            }
            case 95: {
                return jjMoveStringLiteralDfa8_0(active0, 0x40L);
            }
            default: {
                break;
            }
        }
        return jjStartNfa_0(6, active0);
    }

    private int jjMoveStringLiteralDfa8_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L) {
            return jjStartNfa_0(6, old0);
        }
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(7, active0);
            return 8;
        }
        switch (curChar) {
            case 65: {
                return jjMoveStringLiteralDfa9_0(active0, 0x4L);
            }
            case 68: {
                if ((active0 & 0x2L) != 0L)return jjStartNfaWithStates_0(8, 1, 28);
                break;
            }
            case 84: {
                return jjMoveStringLiteralDfa9_0(active0, 0x40L);
            }
            default: {
                break;
            }
        }
        return jjStartNfa_0(7, active0);
    }

    private int jjMoveStringLiteralDfa9_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L) {
            return jjStartNfa_0(7, old0);
        }
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(8, active0);
            return 9;
        }
        switch (curChar) {
            case 79: {
                return jjMoveStringLiteralDfa10_0(active0, 0x40L);
            }
            case 83: {
                return jjMoveStringLiteralDfa10_0(active0, 0x4L);
            }
            default: {
                break;
            }
        }
        return jjStartNfa_0(8, active0);
    }

    private int jjMoveStringLiteralDfa10_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L) {
            return jjStartNfa_0(8, old0);
        }
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(9, active0);
            return 10;
        }
        switch (curChar) {
            case 69: {
                if ((active0 & 0x4L) != 0L)return jjStartNfaWithStates_0(10, 2, 28);
                break;
            }
            case 75: {
                return jjMoveStringLiteralDfa11_0(active0, 0x40L);
            }
            default: {
                break;
            }
        }
        return jjStartNfa_0(9, active0);
    }

    private int jjMoveStringLiteralDfa11_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L) {
            return jjStartNfa_0(9, old0);
        }
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(10, active0);
            return 11;
        }
        switch (curChar) {
            case 69: {
                return jjMoveStringLiteralDfa12_0(active0, 0x40L);
            }
            default: {
                break;
            }
        }
        return jjStartNfa_0(10, active0);
    }

    private int jjMoveStringLiteralDfa12_0(long old0, long active0) {
        if (((active0 &= old0)) == 0L) {
            return jjStartNfa_0(10, old0);
        }
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_0(11, active0);
            return 12;
        }
        switch (curChar) {
            case 78: {
                if ((active0 & 0x40L) != 0L)return jjStartNfaWithStates_0(12, 6, 28);
                break;
            }
            default: {
                break;
            }
        }
        return jjStartNfa_0(11, active0);
    }

    private int jjStartNfaWithStates_0(int pos, int kind, int state) {
        jjmatchedKind = kind;
        jjmatchedPos = pos;
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            return pos + 1;
        }
        return jjMoveNfa_0(state, pos + 1);
    }

    private int jjMoveNfa_0(int startState, int curPos) {
        int startsAt = 0;
        jjnewStateCnt = 61;
        int i = 1;
        jjstateSet[0] = startState;
        int kind = 0x7fffffff;
        for (; ; ) {
            if (++jjround == 0x7fffffff)
                ReInitRounds();
            if (curChar < 64) {
                long l = 1L << curChar;
                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddStates(0, 6);
                            else if (curChar == 36)
                                {
                                if (kind > 60) {
                                    kind = 60;
                                }
                                jjCheckNAdd(28);
                            }
                            else if (curChar == 34)
                                jjCheckNAddStates(7, 9);
                            else if (curChar == 39)
                                jjAddStates(10, 11);
                            else if (curChar == 46)
                                jjCheckNAdd(4);
                            if ((0x3fe000000000000L & l) != 0L)
                                {
                                if (kind > 29) {
                                    kind = 29;
                                }
                                jjCheckNAddTwoStates(1, 2);
                            }
                            else if (curChar == 48)
                                {
                                if (kind > 29) {
                                    kind = 29;
                                }
                                jjCheckNAddStates(12, 16);
                            }
                            break;
                        case 1:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 29) {
                                kind = 29;
                            }
                            jjCheckNAddTwoStates(1, 2);
                            break;
                        case 3:
                            if (curChar == 46)
                                jjCheckNAdd(4);
                            break;
                        case 4:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 33) {
                                kind = 33;
                            }
                            jjCheckNAddStates(17, 19);
                            break;
                        case 6:
                            if ((0x280000000000L & l) != 0L)
                                jjCheckNAdd(7);
                            break;
                        case 7:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 33) {
                                kind = 33;
                            }
                            jjCheckNAddTwoStates(7, 8);
                            break;
                        case 9:
                            if (curChar == 39)
                                jjAddStates(10, 11);
                            break;
                        case 10:
                            if ((0xffffff7fffffdbffL & l) != 0L)
                                jjCheckNAdd(11);
                            break;
                        case 11:
                            if (curChar == 39 && kind > 38)
                                kind = 38;
                            break;
                        case 13:
                            if ((0x8400000000L & l) != 0L)
                                jjCheckNAdd(11);
                            break;
                        case 14:
                            if ((0xff000000000000L & l) != 0L)
                                jjCheckNAddTwoStates(15, 11);
                            break;
                        case 15:
                            if ((0xff000000000000L & l) != 0L)
                                jjCheckNAdd(11);
                            break;
                        case 16:
                            if ((0xf000000000000L & l) != 0L)
                                jjstateSet[jjnewStateCnt++] = 17;
                            break;
                        case 17:
                            if ((0xff000000000000L & l) != 0L)
                                jjCheckNAdd(15);
                            break;
                        case 18:
                            if (curChar == 34)
                                jjCheckNAddStates(7, 9);
                            break;
                        case 19:
                            if ((0xfffffffbffffdbffL & l) != 0L)
                                jjCheckNAddStates(7, 9);
                            break;
                        case 21:
                            if ((0x8400000000L & l) != 0L)
                                jjCheckNAddStates(7, 9);
                            break;
                        case 22:
                            if (curChar == 34 && kind > 39)
                                kind = 39;
                            break;
                        case 23:
                            if ((0xff000000000000L & l) != 0L)
                                jjCheckNAddStates(20, 23);
                            break;
                        case 24:
                            if ((0xff000000000000L & l) != 0L)
                                jjCheckNAddStates(7, 9);
                            break;
                        case 25:
                            if ((0xf000000000000L & l) != 0L)
                                jjstateSet[jjnewStateCnt++] = 26;
                            break;
                        case 26:
                            if ((0xff000000000000L & l) != 0L)
                                jjCheckNAdd(24);
                            break;
                        case 27:
                            if (curChar != 36) {
                                break;
                            }
                            if (kind > 60) {
                                kind = 60;
                            }
                            jjCheckNAdd(28);
                            break;
                        case 28:
                            if ((0x3ff00100fffc1ffL & l) == 0L) {
                                break;
                            }
                            if (kind > 60) {
                                kind = 60;
                            }
                            jjCheckNAdd(28);
                            break;
                        case 29:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddStates(0, 6);
                            break;
                        case 30:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddStates(24, 26);
                            break;
                        case 32:
                            if ((0x280000000000L & l) != 0L)
                                jjCheckNAdd(33);
                            break;
                        case 33:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddTwoStates(33, 8);
                            break;
                        case 34:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddTwoStates(34, 35);
                            break;
                        case 36:
                            if ((0x280000000000L & l) != 0L)
                                jjCheckNAdd(37);
                            break;
                        case 37:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 33) {
                                kind = 33;
                            }
                            jjCheckNAddTwoStates(37, 8);
                            break;
                        case 38:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddTwoStates(38, 39);
                            break;
                        case 39:
                            if (curChar != 46) {
                                break;
                            }
                            if (kind > 33) {
                                kind = 33;
                            }
                            jjCheckNAddStates(27, 29);
                            break;
                        case 40:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 33) {
                                kind = 33;
                            }
                            jjCheckNAddStates(27, 29);
                            break;
                        case 42:
                            if ((0x280000000000L & l) != 0L)
                                jjCheckNAdd(43);
                            break;
                        case 43:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 33) {
                                kind = 33;
                            }
                            jjCheckNAddTwoStates(43, 8);
                            break;
                        case 44:
                            if (curChar != 48) {
                                break;
                            }
                            if (kind > 29) {
                                kind = 29;
                            }
                            jjCheckNAddStates(12, 16);
                            break;
                        case 46:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 29) {
                                kind = 29;
                            }
                            jjCheckNAddTwoStates(46, 2);
                            break;
                        case 47:
                            if ((0xff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 29) {
                                kind = 29;
                            }
                            jjCheckNAddTwoStates(47, 2);
                            break;
                        case 49:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjAddStates(30, 31);
                            break;
                        case 50:
                            if (curChar == 46)
                                jjCheckNAdd(51);
                            break;
                        case 51:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddTwoStates(51, 52);
                            break;
                        case 53:
                            if ((0x280000000000L & l) != 0L)
                                jjCheckNAdd(54);
                            break;
                        case 54:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 33) {
                                kind = 33;
                            }
                            jjCheckNAddTwoStates(54, 8);
                            break;
                        case 56:
                            if ((0x3ff000000000000L & l) != 0L)
                                jjCheckNAddStates(32, 34);
                            break;
                        case 57:
                            if (curChar == 46)
                                jjCheckNAdd(58);
                            break;
                        case 59:
                            if ((0x280000000000L & l) != 0L)
                                jjCheckNAdd(60);
                            break;
                        case 60:
                            if ((0x3ff000000000000L & l) == 0L) {
                                break;
                            }
                            if (kind > 33) {
                                kind = 33;
                            }
                            jjCheckNAddTwoStates(60, 8);
                            break;
                        default: {
                            break;
                        }
                    }
                } while (i != startsAt);
            } else if (curChar < 128) {
                long l = 1L << (curChar & 077);
                do {
                    switch (jjstateSet[--i]) {
                                       case 0:
                            if ((0x7fffffe87fffffeL & l) == 0L) {
                                break;
                            }
                            if (kind > 60) {
                                kind = 60;
                            }
                            jjCheckNAdd(28);
                            break;
                        case 2:
                            if ((0x100000001000L & l) != 0L && kind > 29)
                                kind = 29;
                            break;
                        case 5:
                            if ((0x2000000020L & l) != 0L)
                                jjAddStates(35, 36);
                            break;
                        case 8:
                            if ((0x5000000050L & l) != 0L && kind > 33)
                                kind = 33;
                            break;
                        case 10:
                            if ((0xffffffffefffffffL & l) != 0L)
                                jjCheckNAdd(11);
                            break;
                        case 12:
                            if (curChar == 92)
                                jjAddStates(37, 39);
                            break;
                        case 13:
                            if ((0x14404410000000L & l) != 0L)
                                jjCheckNAdd(11);
                            break;
                        case 19:
                            if ((0xffffffffefffffffL & l) != 0L)
                                jjCheckNAddStates(7, 9);
                            break;
                        case 20:
                            if (curChar == 92)
                                jjAddStates(40, 42);
                            break;
                        case 21:
                            if ((0x14404410000000L & l) != 0L)
                                jjCheckNAddStates(7, 9);
                            break;
                        case 28:
                            if ((0x87fffffe87fffffeL & l) == 0L) {
                                break;
                            }
                            if (kind > 60) {
                                kind = 60;
                            }
                            jjCheckNAdd(28);
                            break;
                        case 31:
                            if ((0x2000000020L & l) != 0L)
                                jjAddStates(43, 44);
                            break;
                        case 35:
                            if ((0x2000000020L & l) != 0L)
                                jjAddStates(45, 46);
                            break;
                        case 41:
                            if ((0x2000000020L & l) != 0L)
                                jjAddStates(47, 48);
                            break;
                        case 45:
                            if ((0x100000001000000L & l) != 0L)
                                jjCheckNAdd(46);
                            break;
                        case 46:
                            if ((0x7e0000007eL & l) == 0L) {
                                break;
                            }
                            if (kind > 29) {
                                kind = 29;
                            }
                            jjCheckNAddTwoStates(46, 2);
                            break;
                        case 48:
                            if ((0x100000001000000L & l) != 0L)
                                jjCheckNAddTwoStates(49, 50);
                            break;
                        case 49:
                            if ((0x7e0000007eL & l) != 0L)
                                jjCheckNAddTwoStates(49, 50);
                            break;
                        case 51:
                            if ((0x7e0000007eL & l) != 0L)
                                jjAddStates(49, 50);
                            break;
                        case 52:
                            if ((0x1000000010000L & l) != 0L)
                                jjAddStates(51, 52);
                            break;
                        case 55:
                            if ((0x100000001000000L & l) != 0L)
                                jjCheckNAdd(56);
                            break;
                        case 56:
                            if ((0x7e0000007eL & l) != 0L)
                                jjCheckNAddStates(32, 34);
                            break;
                        case 58:
                            if ((0x1000000010000L & l) != 0L)
                                jjAddStates(53, 54);
                            break;
                        default: {
                            break;
                        }
                    }
                } while (i != startsAt);
            } else {
                int hiByte = (curChar >> 8);
                int i1 = hiByte >> 6;
                long l1 = 1L << (hiByte & 077);
                int i2 = (curChar & 0xff) >> 6;
                long l2 = 1L << (curChar & 077);
                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                        if (!jjCanMove_1(hiByte, i1, i2, l1, l2))
                            break;
                        if (kind > 60)
                            kind = 60;
                            jjCheckNAdd(28);
                            break;
                        case 10:
                            if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                                jjstateSet[jjnewStateCnt++] = 11;
                                break;
                        case 19:
                            if (jjCanMove_0(hiByte, i1, i2, l1, l2))
                                jjAddStates(7, 9);
                                break;
                        case 28:
                            if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                                break;
                            if (kind > 60)
                                kind = 60;
                                jjCheckNAdd(28);
                                break;
                        default: {
                            break;
                        }
                    }
                } while (i != startsAt);
            }
            if (kind != 0x7fffffff) {
                jjmatchedKind = kind;
                jjmatchedPos = curPos;
                kind = 0x7fffffff;
            }
            curPos++;
            if ((i = jjnewStateCnt) == (startsAt = 61 - (jjnewStateCnt = startsAt)))
                return curPos;
            try {
                curChar = input_stream.readChar();
            } catch (java.io.IOException e) {
                return curPos;
            }
        }
    }

    private int jjMoveStringLiteralDfa0_1() {
        return jjMoveNfa_1(0, 0);
    }

    private int jjMoveNfa_1(int startState, int curPos) {
        int startsAt = 0;
        jjnewStateCnt = 3;
        int i = 1;
        jjstateSet[0] = startState;
        int kind = 0x7fffffff;
        for (; ; ) {
            if (++jjround == 0x7fffffff)
                ReInitRounds();
            if (curChar < 64) {
                long l = 1L << curChar;
                do {
                    switch (jjstateSet[--i]) {
                        case 0:
                            if ((0x2400L & l) != 0L)
                                {
                                if (kind > 18) {
                                    kind = 18;
                                }
                            }
                            if (curChar == 13)
                                jjstateSet[jjnewStateCnt++] = 1;
                            break;
                        case 1:
                            if (curChar == 10 && kind > 18)
                                kind = 18;
                            break;
                        case 2:
                            if (curChar == 13)
                                jjstateSet[jjnewStateCnt++] = 1;
                            break;
                        default: {
                            break;
                        }
                    }
                } while (i != startsAt);
            } else if (curChar < 128) {
                long l = 1L << (curChar & 077);
                do {
                    switch (jjstateSet[--i]) {
                        default: {
                            break;
                        }
                    }
                } while (i != startsAt);
            } else {
                int hiByte = (curChar >> 8);
                int i1 = hiByte >> 6;
                long l1 = 1L << (hiByte & 077);
                int i2 = (curChar & 0xff) >> 6;
                long l2 = 1L << (curChar & 077);
                do {
                    switch (jjstateSet[--i]) {
                        default: {
                            break;
                        }
                    }
                } while (i != startsAt);
            }
            if (kind != 0x7fffffff) {
                jjmatchedKind = kind;
                jjmatchedPos = curPos;
                kind = 0x7fffffff;
            }
            curPos++;
            if ((i = jjnewStateCnt) == (startsAt = 3 - (jjnewStateCnt = startsAt)))
                return curPos;
            try {
                curChar = input_stream.readChar();
            } catch (java.io.IOException e) {
                return curPos;
            }
        }
    }

    private int jjMoveStringLiteralDfa0_2() {
        switch (curChar) {
            case 42: {
                return jjMoveStringLiteralDfa1_2(0x80000L);
            }
            default: {
                return 1;
            }
        }
    }

    private int jjMoveStringLiteralDfa1_2(long active0) {
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            return 1;
        }
        switch (curChar) {
            case 47: {
                if ((active0 & 0x80000L) != 0L)return jjStopAtPos(1, 19);
                break;
            }
            default: {
                return 2;
            }
        }
        return 2;
    }

    private final int jjStopStringLiteralDfa_3(int pos, long active0) {
        switch (pos) {
            case 0:
                if ((active0 & 0x100000L) != 0L)
                    return 2;
                return -1;
            default:
                return -1;
        }
    }

    private final int jjStartNfa_3(int pos, long active0) {
        return jjMoveNfa_3(jjStopStringLiteralDfa_3(pos, active0), pos + 1);
    }

    private int jjMoveStringLiteralDfa0_3() {
        switch (curChar) {
            case 63: {
                return jjMoveStringLiteralDfa1_3(0x100000L);
            }
            default: {
                return jjMoveNfa_3(3, 0);
            }
        }
    }

    private int jjMoveStringLiteralDfa1_3(long active0) {
        try {
            curChar = input_stream.readChar();
        } catch (java.io.IOException e) {
            jjStopStringLiteralDfa_3(0, active0);
            return 1;
        }
        switch (curChar) {
            case 62: {
                if ((active0 & 0x100000L) != 0L)return jjStopAtPos(1, 20);
                break;
            }
            default: {
                break;
            }
        }
        return jjStartNfa_3(0, active0);
    }

    private int jjMoveNfa_3(int startState, int curPos) {
        int startsAt = 0;
        jjnewStateCnt = 3;
        int i = 1;
        jjstateSet[0] = startState;
        int kind = 0x7fffffff;
        for (; ; ) {
            if (++jjround == 0x7fffffff)
                ReInitRounds();
            if (curChar < 64) {
                long l = 1L << curChar;
                do {
                    switch (jjstateSet[--i]) {
                        case 3:
                            if ((0x7fffffffffffffffL & l) != 0L)
                                {
                                if (kind > 21) {
                                    kind = 21;
                                }
                                jjCheckNAddTwoStates(0, 1);
                            }
                            else if (curChar == 63)
                                jjstateSet[jjnewStateCnt++] = 2;
                            break;
                        case 0:
                            if ((0x7fffffffffffffffL & l) == 0L) {
                                break;
                            }
                            if (kind > 21) {
                                kind = 21;
                            }
                            jjCheckNAddTwoStates(0, 1);
                            break;
                        case 1:
                            if (curChar == 63)
                                jjstateSet[jjnewStateCnt++] = 2;
                            break;
                        case 2:
                            if ((0xbfffffffffffffffL & l) == 0L) {
                                break;
                            }
                            if (kind > 21) {
                                kind = 21;
                            }
                            jjCheckNAddTwoStates(0, 1);
                            break;
                        default: {
                            break;
                        }
                    }
                } while (i != startsAt);
            } else if (curChar < 128) {
                long l = 1L << (curChar & 077);
                do {
                    switch (jjstateSet[--i]) {
                                       case 3:
                                       case 0:
                        case 2:
                            if (kind > 21) {
                                kind = 21;
                            }
                            jjCheckNAddTwoStates(0, 1);
                            break;
                        default: {
                            break;
                        }
                    }
                } while (i != startsAt);
            } else {
                int hiByte = (curChar >> 8);
                int i1 = hiByte >> 6;
                long l1 = 1L << (hiByte & 077);
                int i2 = (curChar & 0xff) >> 6;
                long l2 = 1L << (curChar & 077);
                do {
                    switch (jjstateSet[--i]) {
                        case 3:
                        case 0:
                        case 2:
                        if (!jjCanMove_0(hiByte, i1, i2, l1, l2))
                            break;
                        if (kind > 21)
                            kind = 21;
                            jjCheckNAddTwoStates(0, 1);
                            break;
                        default: {
                            break;
                        }
                    }
                } while (i != startsAt);
            }
            if (kind != 0x7fffffff) {
                jjmatchedKind = kind;
                jjmatchedPos = curPos;
                kind = 0x7fffffff;
            }
            curPos++;
            if ((i = jjnewStateCnt) == (startsAt = 3 - (jjnewStateCnt = startsAt)))
                return curPos;
            try {
                curChar = input_stream.readChar();
            } catch (java.io.IOException e) {
                return curPos;
            }
        }
    }

    /**
     * Token literal values.
     */
    public static String[] jjstrLiteralImages = {
        "", "\114\117\117\113\101\110\105\101\104", 
        "\111\107\116\117\122\105\137\103\101\123\105", "\147\162\141\155\155\141\162", "\157\160\164\151\157\156\163", 
        "\124\117\113\105\116", "\123\120\105\103\111\101\114\137\124\117\113\105\116", "\115\117\122\105", 
        "\123\113\111\120", "\105\117\106", null, null, null, null, null, null, null, null, null, null, 
        null, null, null, "\142\157\157\154\145\141\156", "\151\156\164", 
        "\143\150\141\162", "\156\165\154\154", "\164\162\165\145", "\146\141\154\163\145", null, null, 
        null, null, null, null, null, null, null, null, null, "\50", "\51", "\173", "\175", 
        "\133", "\135", "\54", "\73", "\56", "\75", "\76", "\74", "\176", "\77", "\43", "\72", 
        "\53", "\55", "\52", "\174", null, null, null, 
    };

    protected Token jjFillToken() {
        final Token t;
        final String curTokenImage;
        final int beginLine;
        final int endLine;
        final int beginColumn;
        final int endColumn;
        String im = jjstrLiteralImages[jjmatchedKind];
        curTokenImage = (im == null) ? input_stream.GetImage() : im;
        beginLine = input_stream.getBeginLine();
        beginColumn = input_stream.getBeginColumn();
        endLine = input_stream.getEndLine();
        endColumn = input_stream.getEndColumn();
        t = new Token(jjmatchedKind, curTokenImage);
        t.beginLine = beginLine;
        t.endLine = endLine;
        t.beginColumn = beginColumn;
        t.endColumn = endColumn;
        return t;
    }

    static final int[] jjnextStates = {
        30, 31, 8, 34, 35, 38, 39, 19, 20, 22, 10, 12, 45, 47, 2, 48, 
        55, 4, 5, 8, 19, 20, 24, 22, 30, 31, 8, 40, 41, 8, 49, 50, 
        56, 57, 58, 6, 7, 13, 14, 16, 21, 23, 25, 32, 33, 36, 37, 42, 
        43, 51, 52, 53, 54, 59, 60, 
    };

    private static boolean jjCanMove_0(int hiByte, int i1, int i2, long l1, long l2) {
        switch (hiByte) {
            case 0:
                return ((jjbitVec2[i2] & l2) != 0L);
            default:
                if ((jjbitVec0[i1] & l1) != 0L)
                    return true;
            return false;
        }
    }

    private static boolean jjCanMove_1(int hiByte, int i1, int i2, long l1, long l2) {
        switch (hiByte) {
            case 0:
                return ((jjbitVec3[i2] & l2) != 0L);
            default:
                if ((jjbitVec0[i1] & l1) != 0L)
                    return true;
            return false;
        }
    }


    int curLexState = 0;
    int defaultLexState = 0;
    int jjnewStateCnt;
    int jjround;
    int jjmatchedPos;
    int jjmatchedKind;

    /**
     * Get the next Token.
     */
    public Token getNextToken() {
        Token specialToken = null;
        Token matchedToken;
        int curPos = 0;

        EOFLoop:
        for (; ; ) {
            try {
                curChar = input_stream.BeginToken();
            } catch (Exception e) {
                jjmatchedKind = 0;
                jjmatchedPos = -1;
                matchedToken = jjFillToken();
                matchedToken.specialToken = specialToken;
                return matchedToken;
            }
            image = jjimage;
            image.setLength(0);
            jjimageLen = 0;

            for (; ; ) {
                switch (curLexState) {
                    case 0: {
                        try {
                            while (curChar <= 32 && (0x100003600L & (1L << curChar)) != 0L)
                            curChar = input_stream.BeginToken();
                        } catch (java.io.IOException e1) { continue EOFLoop; }
                        jjmatchedKind = 0x7fffffff;
                        jjmatchedPos = 0;
                        curPos = jjMoveStringLiteralDfa0_0();
                        break;
                    }
                    case 1: {
                        jjmatchedKind = 0x7fffffff;
                        jjmatchedPos = 0;
                        curPos = jjMoveStringLiteralDfa0_1();
                        if (jjmatchedPos == 0 && jjmatchedKind > 22) {
                            jjmatchedKind = 22;
                        }
                        break;
                    }
                    case 2: {
                        jjmatchedKind = 0x7fffffff;
                        jjmatchedPos = 0;
                        curPos = jjMoveStringLiteralDfa0_2();
                        if (jjmatchedPos == 0 && jjmatchedKind > 22) {
                            jjmatchedKind = 22;
                        }
                        break;
                    }
                    case 3: {
                        jjmatchedKind = 0x7fffffff;
                        jjmatchedPos = 0;
                        curPos = jjMoveStringLiteralDfa0_3();
                        break;
                    }
                }
                if (jjmatchedKind != 0x7fffffff) {
                    if (jjmatchedPos + 1 < curPos) {
                        input_stream.backup(curPos - jjmatchedPos - 1);
                    }
                    if ((jjtoToken[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L) {
                        matchedToken = jjFillToken();
                        matchedToken.specialToken = specialToken;
                        if (jjnewLexState[jjmatchedKind] != -1)
                            curLexState = jjnewLexState[jjmatchedKind];
                        return matchedToken;
                    }
                    else if ((jjtoSkip[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L) {
                        if ((jjtoSpecial[jjmatchedKind >> 6] & (1L << (jjmatchedKind & 077))) != 0L) {
                            matchedToken = jjFillToken();
                            if (specialToken == null)
                                specialToken = matchedToken;
                            else {
                                matchedToken.specialToken = specialToken;
                                specialToken = (specialToken.next = matchedToken);
                            }
                            SkipLexicalActions(matchedToken);
                        } else
                            SkipLexicalActions(null);
                        if (jjnewLexState[jjmatchedKind] != -1)
                            curLexState = jjnewLexState[jjmatchedKind];
                        continue EOFLoop;
                    }
                    jjimageLen += jjmatchedPos + 1;
                    if (jjnewLexState[jjmatchedKind] != -1)
                        curLexState = jjnewLexState[jjmatchedKind];
                    curPos = 0;
                    jjmatchedKind = 0x7fffffff;
                    try {
                        curChar = input_stream.readChar();
                        continue;
                    } catch (java.io.IOException e1) {
                    }
                }
                int error_line = input_stream.getEndLine();
                int error_column = input_stream.getEndColumn();
                String error_after = null;
                boolean EOFSeen = false;
                try {
                    input_stream.readChar();
                    input_stream.backup(1);
                } catch (java.io.IOException e1) {
                    EOFSeen = true;
                    error_after = curPos <= 1 ? "" : input_stream.GetImage();
                    if (curChar == '\n' || curChar == '\r') {
                        error_line++;
                        error_column = 0;
                    } else
                        error_column++;
                }
                if (!EOFSeen) {
                    input_stream.backup(1);
                    error_after = curPos <= 1 ? "" : input_stream.GetImage();
                }
                throw new TokenException(EOFSeen, curLexState, error_line, error_column, error_after, curChar, TokenException.LEXICAL_ERROR);
            }
        }
    }

    void SkipLexicalActions(Token matchedToken) {
        switch (jjmatchedKind) {
            default:
                break;
        }
    }

    void MoreLexicalActions() {
        jjimageLen += (jjmatchedPos + 1);
        switch (jjmatchedKind) {
            default:
                break;
        }
    }

    void TokenLexicalActions(Token matchedToken) {
        switch (jjmatchedKind) {
            default:
                break;
        }
    }

    private void jjCheckNAdd(int state) {
        if (jjrounds[state] != jjround) {
            jjstateSet[jjnewStateCnt++] = state;
            jjrounds[state] = jjround;
        }
    }

    private void jjAddStates(int start, int end) {
        do {
            jjstateSet[jjnewStateCnt++] = jjnextStates[start];
        } while (start++ != end);
    }

    private void jjCheckNAddTwoStates(int state1, int state2) {
        jjCheckNAdd(state1);
        jjCheckNAdd(state2);
    }

    private void jjCheckNAddStates(int start, int end) {
        do {
            jjCheckNAdd(jjnextStates[start]);
        } while (start++ != end);
    }


    /**
     * Constructor.
     */
    public Lexer(JavaCharStream stream) {
        input_stream = stream;
    }

    /**
     * Constructor.
     */
    public Lexer(JavaCharStream stream, int lexState) {
        ReInit(stream);
        SwitchTo(lexState);
    }

    /**
     * Reinitialise parser.
     */
    public void ReInit(JavaCharStream stream) {
        jjmatchedPos = 0;
        jjnewStateCnt = 0;
        curLexState = defaultLexState;
        input_stream = stream;
        ReInitRounds();
    }

    private void ReInitRounds() {
        int i;
        jjround = 0x80000001;
        for (i = 61; i-- > 0; ) {
            jjrounds[i] = 0x80000000;
        }
    }

    /**
     * Reinitialise parser.
     */
    public void ReInit(JavaCharStream stream, int lexState) {
        ReInit(stream);
        SwitchTo(lexState);
    }

    /**
     * Switch to specified lex state.
     */
    public void SwitchTo(int lexState) {
        if (lexState >= 4 || lexState < 0)
            throw new TokenException(
                    "Error: Ignoring invalid lexical state : " + lexState + ". State unchanged.",
                    TokenException.INVALID_LEXICAL_STATE);
        else
            curLexState = lexState;
    }

    /**
     * Lexer state names.
     */
    public static String[] lexStateNames = {
            "DEFAULT",
            "IN_SINGLE_LINE_COMMENT",
            "IN_MULTI_LINE_COMMENT",
            "PARSER_CODE",
    };

    public static final int[] jjnewLexState = {
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 1, 2, 3, 0, 0, 0, -1, -1, -1, -1, 
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
        -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 
    };
    static final long[] jjtoToken = {
        0x1fffffc23fb003ffL, 
    };
    static final long[] jjtoSkip = {
        0xc7c00L, 
    };
    static final long[] jjtoSpecial = {
        0xc0000L, 
    };
    static final long[] jjtoMore = {
        0x438000L, 
    };

    private       JavaCharStream input_stream;
    private final int[]          jjrounds   = new int[61];
    private final int[]          jjstateSet = new int[122];
    private final StringBuilder  jjimage    = new StringBuilder();
    private       StringBuilder  image      = jjimage;
    private       int            jjimageLen;
    private       int            lengthOfMatch;
    protected     int            curChar;
}

// Checksum=078DB99E494085054D208D6DE6C3724D (Do not edit this line!)
