// Generated by HiveVM Waggle v.1.0 - Do not edit this line!

// Copyright 2024 HiveVM.ORG. All rights reserved.
// Copyright (c) 2006, Sun Microsystems, Inc. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Derived from JavaCC 7.0.12: src/main/resources/templates/SimpleNode.template

package org.hivevm.waggle.grammar;

public class Node {

    private final int    id;
    private final Parser parser;

    private Node   parent;
    private Node[] children;
    private Object value;

    public Node(Parser p, int i) {
        this.id = i;
        this.parser = p;
    }

    public int getId() {
        return this.id;
    }

    public Parser jjtParser() {
        return parser;
    }

    public void jjtOpen() {
    }

    public void jjtClose() {
    }

    public void jjtSetParent(Node n) {
        this.parent = n;
    }

    public Node jjtGetParent() {
        return this.parent;
    }

    public void jjtAddChild(Node n, int i) {
        if (this.children == null) {
            this.children = new Node[i + 1];
        } else if (i >= this.children.length) {
            Node[] c = new Node[i + 1];
            System.arraycopy(this.children, 0, c, 0, this.children.length);
            this.children = c;
        }
        this.children[i] = n;
    }

    public Node jjtGetChild(int i) {
        return this.children[i];
    }

    public int jjtGetNumChildren() {
        return (this.children == null) ? 0 : this.children.length;
    }

    public void jjtSetValue(Object value) {
        this.value = value;
    }

    public Object jjtGetValue() {
        return this.value;
    }


    /**
     * Accept the visitor.
     **/
    public Object jjtAccept(NodeVisitor visitor, Object data) {
        return visitor.visit(this, data);
    }

    /**
     * Accept the visitor.
     **/
    public Object childrenAccept(NodeVisitor visitor, Object data) {
        if (children != null) {
            for (int i = 0; i < children.length; ++i) {
                children[i].jjtAccept(visitor, data);
            }
        }
        return data;
    }

    /*
     * You can override these two methods in subclasses of Node to customize the way the node appears
     * when the tree is dumped. If your output uses more than one line you should override
     * toString(String), otherwise overriding toString() is probably all you need to do.
     */

    @Override
    public String toString() {
        return NodeType.jjtNodeName[this.id];
    }

    public String toString(String prefix) {
        return prefix + this;
    }

    /*
     * Override this method if you want to customize how the node dumps out its children.
     */

    public void dump(String prefix) {
        System.out.println(toString(prefix));
        if (this.children != null) {
            for (Node child : this.children) {
                Node n = child;
                if (n != null) {
                    n.dump(prefix + " ");
                }
            }
        }
    }
}

// Checksum=E3D5C957B2D2B42979E49FB026832FDB (Do not edit this line!)
