// Generated by HiveVM Waggle v.1.0 - Do not edit this line!

// Copyright 2024 HiveVM.ORG. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause

package org.hivevm.waggle.grammar;

public interface NodeType {
    int JJTGRAMMAR = 0;
    int JJTCOMPILATIONUNIT = 1;
    int JJTOPTIONBINDING = 2;
    int JJTREPRODUCTION = 3;
    int JJTRESPEC = 4;
    int JJTBNF = 5;
    int JJTBNFDECLARATION = 6;
    int JJTBNFNODESCOPE = 7;
    int JJTBNFCHOICE = 8;
    int JJTBNFSEQUENCE = 9;
    int JJTBNFLOOKAHEAD = 10;
    int JJTBNFEXPANSIONSCOPE = 11;
    int JJTBNFACTION = 12;
    int JJTBNFZEROORONE = 13;
    int JJTBNFNONTERMINAL = 14;
    int JJTBNFASSIGNMENT = 15;
    int JJTBNFONEORMORE = 16;
    int JJTBNFZEROORMORE = 17;
    int JJTRESTRINGLITERAL = 18;
    int JJTRENAMED = 19;
    int JJTREREFERENCE = 20;
    int JJTREEOF = 21;
    int JJTRECHOICE = 22;
    int JJTRESEQUENCE = 23;
    int JJTREONEORMORE = 24;
    int JJTREZEROORMORE = 25;
    int JJTREZEROORONE = 26;
    int JJTRREPETITIONRANGE = 27;
    int JJTRECHARLIST = 28;
    int JJTCHARDESCRIPTOR = 29;
    int JJTNODEDESCRIPTOR = 30;
    int JJTEXPRESSION = 31;

    String[] jjtNodeName = {
            "Grammar",
            "CompilationUnit",
            "OptionBinding",
            "REProduction",
            "RESpec",
            "BNF",
            "BNFDeclaration",
            "BNFNodeScope",
            "BNFChoice",
            "BNFSequence",
            "BNFLookahead",
            "BNFExpansionScope",
            "BNFAction",
            "BNFZeroOrOne",
            "BNFNonTerminal",
            "BNFAssignment",
            "BNFOneOrMore",
            "BNFZeroOrMore",
            "REStringLiteral",
            "RENamed",
            "REReference",
            "REEOF",
            "REChoice",
            "RESequence",
            "REOneOrMore",
            "REZeroOrMore",
            "REZeroOrOne",
            "RRepetitionRange",
            "RECharList",
            "CharDescriptor",
            "NodeDescriptor",
            "Expression",
    };
}

// Checksum=037300A3FBFF2F22AE7AA314C23FE539 (Do not edit this line!)
