// Generated by HiveVM Waggle v.1.0 - Do not edit this line!

// Copyright 2024 HiveVM.ORG. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause

package org.hivevm.waggle.grammar;

public interface NodeVisitor {

    Object visit(Node node, Object data);

    Object visit(ASTGrammar node, Object data);

    Object visit(ASTCompilationUnit node, Object data);

    Object visit(ASTOptionBinding node, Object data);

    Object visit(ASTREProduction node, Object data);

    Object visit(ASTRESpec node, Object data);

    Object visit(ASTBNF node, Object data);

    Object visit(ASTBNFDeclaration node, Object data);

    Object visit(ASTBNFNodeScope node, Object data);

    Object visit(ASTBNFChoice node, Object data);

    Object visit(ASTBNFSequence node, Object data);

    Object visit(ASTBNFLookahead node, Object data);

    Object visit(ASTBNFExpansionScope node, Object data);

    Object visit(ASTBNFAction node, Object data);

    Object visit(ASTBNFZeroOrOne node, Object data);

    Object visit(ASTBNFNonTerminal node, Object data);

    Object visit(ASTBNFAssignment node, Object data);

    Object visit(ASTBNFOneOrMore node, Object data);

    Object visit(ASTBNFZeroOrMore node, Object data);

    Object visit(ASTREStringLiteral node, Object data);

    Object visit(ASTRENamed node, Object data);

    Object visit(ASTREReference node, Object data);

    Object visit(ASTREEOF node, Object data);

    Object visit(ASTREChoice node, Object data);

    Object visit(ASTRESequence node, Object data);

    Object visit(ASTREOneOrMore node, Object data);

    Object visit(ASTREZeroOrMore node, Object data);

    Object visit(ASTREZeroOrOne node, Object data);

    Object visit(ASTRRepetitionRange node, Object data);

    Object visit(ASTRECharList node, Object data);

    Object visit(ASTCharDescriptor node, Object data);

    Object visit(ASTNodeDescriptor node, Object data);

    Object visit(ASTExpression node, Object data);
}
// Checksum=FEC1AC88EB1D1618469F3C80A43F238D (Do not edit this line!)
