// Generated by HiveVM Waggle v.1.0 - Do not edit this line!

// Copyright 2024 HiveVM.ORG. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause

package org.hivevm.waggle.grammar;

public class NodeDefaultVisitor implements NodeVisitor {

    public Object defaultVisit(Node node, Object data) {
        node.childrenAccept(this, data);
        return data;
    }

    public Object visit(Node node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTGrammar node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTCompilationUnit node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTOptionBinding node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTREProduction node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTRESpec node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNF node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFDeclaration node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFNodeScope node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFChoice node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFSequence node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFLookahead node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFExpansionScope node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFAction node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFZeroOrOne node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFNonTerminal node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFAssignment node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFOneOrMore node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTBNFZeroOrMore node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTREStringLiteral node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTRENamed node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTREReference node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTREEOF node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTREChoice node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTRESequence node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTREOneOrMore node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTREZeroOrMore node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTREZeroOrOne node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTRRepetitionRange node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTRECharList node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTCharDescriptor node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTNodeDescriptor node, Object data) {
        return defaultVisit(node, data);
    }

    public Object visit(ASTExpression node, Object data) {
        return defaultVisit(node, data);
    }
}
// Checksum=56ABD07CCCE9ACFE4FE0FADAEF6C4054 (Do not edit this line!)
