// Generated by HiveVM Waggle v.1.0 - Do not edit this line!

// Copyright 2024 HiveVM.ORG. All rights reserved.
// Copyright (c) 2006, Sun Microsystems, Inc. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Derived from JavaCC 7.0.12: test/javaFileGeneration/expected/non-static/ParserConstants.java, test/javaFileGeneration/expected/static/ParserConstants.java

package org.hivevm.waggle.grammar;

/**
 * Token literal values and constants. Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

    // End of File
    int EOF = 0;

    // RegularExpression Ids
    int _LOOKAHEAD = 1;
    int _IGNORE_CASE = 2;
    int _GRAMMAR = 3;
    int _OPTIONS = 4;
    int _TOKEN = 5;
    int _SPECIAL_TOKEN = 6;
    int _MORE = 7;
    int _SKIP = 8;
    int _EOF = 9;
    int SINGLE_LINE_COMMENT = 18;
    int MULTI_LINE_COMMENT = 19;
    int ECODE_END = 20;
    int ECODE_DATA = 21;
    int BOOLEAN = 23;
    int INT = 24;
    int CHAR = 25;
    int NULL = 26;
    int TRUE = 27;
    int FALSE = 28;
    int INTEGER_LITERAL = 29;
    int DECIMAL_LITERAL = 30;
    int HEX_LITERAL = 31;
    int OCTAL_LITERAL = 32;
    int FLOATING_POINT_LITERAL = 33;
    int DECIMAL_FLOATING_POINT_LITERAL = 34;
    int DECIMAL_EXPONENT = 35;
    int HEXADECIMAL_FLOATING_POINT_LITERAL = 36;
    int HEXADECIMAL_EXPONENT = 37;
    int CHARACTER_LITERAL = 38;
    int STRING_LITERAL = 39;
    int LPAREN = 40;
    int RPAREN = 41;
    int LBRACE = 42;
    int RBRACE = 43;
    int LBRACKET = 44;
    int RBRACKET = 45;
    int COMMA = 46;
    int SEMICOLON = 47;
    int DOT = 48;
    int ASSIGN = 49;
    int GT = 50;
    int LT = 51;
    int TILDE = 52;
    int HOOK = 53;
    int HASH = 54;
    int COLON = 55;
    int PLUS = 56;
    int MINUS = 57;
    int STAR = 58;
    int BIT_OR = 59;
    int IDENTIFIER = 60;
    int LETTER = 61;
    int PART_LETTER = 62;

    // Lexical states
    int DEFAULT = 0;
    int IN_SINGLE_LINE_COMMENT = 1;
    int IN_MULTI_LINE_COMMENT = 2;
    int PARSER_CODE = 3;

    // Literal token values
    String[] tokenImage = {
            "<EOF>",
            "\"LOOKAHEAD\"",
            "\"IGNORE_CASE\"",
            "\"grammar\"",
            "\"options\"",
            "\"TOKEN\"",
            "\"SPECIAL_TOKEN\"",
            "\"MORE\"",
            "\"SKIP\"",
            "\"EOF\"",
            "\" \"",
            "\"\\t\"",
            "\"\\n\"",
            "\"\\r\"",
            "\"\\f\"",
            "\"//\"",
            "\"/*\"",
            "\"<?\"",
            "<SINGLE_LINE_COMMENT>",
            "\"*/\"",
            "\"?>\"",
            "<ECODE_DATA>",
            "<token of kind 22>",
            "\"boolean\"",
            "\"int\"",
            "\"char\"",
            "\"null\"",
            "\"true\"",
            "\"false\"",
            "<INTEGER_LITERAL>",
            "<DECIMAL_LITERAL>",
            "<HEX_LITERAL>",
            "<OCTAL_LITERAL>",
            "<FLOATING_POINT_LITERAL>",
            "<DECIMAL_FLOATING_POINT_LITERAL>",
            "<DECIMAL_EXPONENT>",
            "<HEXADECIMAL_FLOATING_POINT_LITERAL>",
            "<HEXADECIMAL_EXPONENT>",
            "<CHARACTER_LITERAL>",
            "<STRING_LITERAL>",
            "\"(\"",
            "\")\"",
            "\"{\"",
            "\"}\"",
            "\"[\"",
            "\"]\"",
            "\",\"",
            "\";\"",
            "\".\"",
            "\"=\"",
            "\">\"",
            "\"<\"",
            "\"~\"",
            "\"?\"",
            "\"#\"",
            "\":\"",
            "\"+\"",
            "\"-\"",
            "\"*\"",
            "\"|\"",
            "<IDENTIFIER>",
            "<LETTER>",
            "<PART_LETTER>"
    };
}

// Checksum=DBEB6841402FE6570D08E476D22B8514 (Do not edit this line!)
