// Copyright 2024 HiveVM.ORG. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause

/**
 * The reference consumer of tree building — not a stage of the pipeline.
 *
 * <p>JJTree is JavaCC's separate pre-processor: it read a {@code .jjt} grammar, rewrote it into an
 * annotated {@code .jj} grammar, and only then ran the parser generator. HiveVM Waggle does not work
 * that way. {@code #Node} descriptors are part of the one grammar and the tree is generated in the
 * same pass as the parser ({@link org.hivevm.waggle.model.NodeScope}, ADR-0010). Nothing in this
 * package runs before, or instead of, that pass.
 *
 * <p>What survives here is a grammar for the grammar language itself, {@code JJTree.waggle},
 * generated by the {@code tree} task of the build into {@code org.hivevm.waggle.jjtree}, together
 * with the hand-written classes that consume the result — the {@link ASTNode} hierarchy, {@link ASTParser}, {@link ASTWriter} and
 * {@link TreeGenerator}.
 *
 * <p>Its purpose is dogfooding. This is the only grammar in the repository that exercises the tree
 * features end to end: {@code #Node} descriptors, {@code NODE_MULTI}, {@code VISITOR},
 * {@code NODE_SCOPE_HOOK} and {@code BASE_PARSER}. If tree building breaks, it breaks here first,
 * in a grammar the build regenerates on every run — which is why the package stays even though no
 * production code path depends on it.
 */
package org.hivevm.waggle.jjtree;

