PARSER(
  PARSER_NAME: "JJTreeParser",
  NODE_MULTI: true,
  NODE_DEFAULT_VOID: true,
  NODE_SCOPE_HOOK: true,
  NODE_CLASS: "ASTNode",
  VISITOR: true,
  VISITOR_DATA_TYPE: "ASTWriter",
  JAVA_PACKAGE: "org.hivevm.cc.jjtree",
  JAVA_IMPORTS: "org.hivevm.cc.model.NodeScope",
  BASE_PARSER: "ASTParser"
)


/************************************************
 * THE JAVACC GRAMMAR SPECIFICATION STARTS HERE *
 ************************************************/
RULE javacc_input() #Grammar ::=
  ( < _PARSER > < LPAREN > option_binding() (< COMMA > option_binding())* < RPAREN > ) #CompilationUnit(true)
  (bnf_production()) +
  <EOF>
};

RULE option_binding() #OptionBinding ::=
  <? Token t; ?>
  t=<IDENTIFIER> < COLON > ( IntegerLiteral() | BooleanLiteral() | StringLiteral() )
  <? jjtree.closeNodeScope($NODE, true);
    $BOOL = false;
    if (jjtree.nodeCreated()) {
     jjtreeCloseNodeScope($NODE);
    }?>
  <? setInputOption(t, this.token); ?>
};

RULE bnf_production() #BNF ::=
<?
    Token t1;
    ASTBNF prod = $NODE;
    ASTNodeDescriptor nd = null;
    JJTNodeScope ns;
    ASTNode eu;
?>
  < _RULE >
  t1=identifier() < LPAREN > [ FormalParameter() ( < COMMA > FormalParameter() )* ] < RPAREN >
  [ < COLON > Type() ]
  [ nd=node_descriptor() ]
<?
    prod.setName(t1.image);
    ns = new JJTNodeScope(prod, nd);
?>
  ( <? jjtree.closeNodeScope($NODE, true);
    $BOOL = false;
    if (jjtree.nodeCreated()) {
     jjtreeCloseNodeScope($NODE);
    }?>
    <? $NODE.node_scope = ns;?> ) #BNFDeclaration
  < ASSIGN_OP >
  (
    eu=expansion_choices(prod)
<? jjtree.closeNodeScope($NODE, true);
      $BOOL = false;
      if (jjtree.nodeCreated()) {
       jjtreeCloseNodeScope($NODE);
      }?>
<?
      $NODE.node_scope = ns;
      $NODE.expansion_unit = eu;
?>
  ) #BNFNodeScope
  < RBRACE > < SEMICOLON >
  <? jjtree.closeNodeScope($NODE, true);
    $BOOL = false;
    if (jjtree.nodeCreated()) {
     jjtreeCloseNodeScope($NODE);
    }?>
  <? addProduction(prod); ?>
};

RULE expansion_choices(ASTProduction p) : ASTNode #BNFChoice(>1) ::=
  expansion(p) ( < BIT_OR > expansion(p) )*
  <? jjtree.closeNodeScope($NODE, jjtree.nodeArity() >1);
    $BOOL = false;
    if (jjtree.nodeCreated()) {
     jjtreeCloseNodeScope($NODE);
    }?>
  <? return (ASTNode)jjtree.peekNode(); ?>
};

RULE expansion(ASTProduction p) #BNFSequence(>1) ::=
<?
    ASTNode eu;
    ASTNodeDescriptor nd = null;
?>
  ( LOOKAHEAD(1) ( < _LOOKAHEAD > < LPAREN > local_lookahead(p) < RPAREN > ) #BNFLookahead )?
  ( LOOKAHEAD(0, { notTailOfExpansionUnit() } )
    (
      eu=expansion_unit(p)
      [ nd=node_descriptor() ]
<?
        jjtree.closeNodeScope($NODE, jjtree.nodeArity() >1);
        $BOOL = false;
        if (jjtree.nodeCreated()) {
         jjtreeCloseNodeScope($NODE);
        }
        if (jjtree.nodeCreated()) {
          $NODE.node_scope = new JJTNodeScope(p, nd);
          $NODE.expansion_unit = eu;
        }
?>
    ) #BNFExpansionScope(>1)
  )+
};

RULE local_lookahead(ASTProduction p) ::=
<?
    boolean commaAtEnd = false;
    boolean emptyLA = true;
?>
  [
    /*
     * The lookahead of 1 is to turn off the warning message that lets
     * us know that an expansion choice can also start with an integer
     * literal because a primary expression can do the same.  But we
     * know that this is what we want.
     */
    LOOKAHEAD(1)
    IntegerLiteral()
    <? emptyLA = false; ?>
  ]
  [ LOOKAHEAD(0, { checkEmptyLA(emptyLA, getToken(1)) } )
    < COMMA > <? commaAtEnd = true; ?>
  ]
  [ LOOKAHEAD(0, { checkEmpty(getToken(1)) } )
    expansion_choices(p)
    <? emptyLA = false; commaAtEnd = false; ?>
  ]
  [ LOOKAHEAD(0, { checkEmptyLAAndCommandEnd(emptyLA, commaAtEnd, getToken(1)) } )
    < COMMA > <? commaAtEnd = true; ?>
  ]
  [ LOOKAHEAD(0, { checkEmptyLAOrCommandEnd(emptyLA, commaAtEnd) } )
    < LBRACE > [ Expression() ] < RBRACE >
  ]
};

RULE expansion_unit(ASTProduction p) : ASTNode ::=
<? Token t; ?>
(
  LOOKAHEAD(1)
  /*
   * We give this priority over primary expressions which use LOOKAHEAD as the
   * name of its identifier.
   */
  ( < _LOOKAHEAD > < LPAREN > local_lookahead(p) < RPAREN > ) #BNFLookahead
| Statement() #BNFAction
| ( < LBRACKET > expansion_choices(p) < RBRACKET > ) #BNFZeroOrOne
| LOOKAHEAD( identifier() | StringLiteral() | < LT > | Expression() < ASSIGN > )
(
  [
    LOOKAHEAD(Expression() < ASSIGN >)
    Expression() < ASSIGN >
  ]
  (
    regular_expression() [ < DOT > t=<IDENTIFIER>  ]
  | ( identifier() Arguments() ) #BNFNonTerminal
  )
) #BNFAssignment(>1)
|
  t=< LPAREN > expansion_choices(p) < RPAREN >
  (
    < PLUS > #BNFOneOrMore(1)
  | < STAR > #BNFZeroOrMore(1)
  | < HOOK > #BNFZeroOrOne(1)
  | {} <? jjtree.closeNodeScope($NODE, 1);
    $BOOL = false;
    if (jjtree.nodeCreated()) {
     jjtreeCloseNodeScope($NODE);
    }?> #BNFParenthesized(1)

  )
  <? ((ASTNode)jjtree.peekNode()).setFirstToken(t); ?>
)
<? return (ASTNode)jjtree.peekNode(); ?>
};

RULE regular_expression() ::=
  StringLiteral() #REStringLiteral
|
  LOOKAHEAD(3)
  (
    < LT > [ [ < HASH > ] identifier() < COLON > ] complex_regular_expression_choices() < GT >
  ) #RENamed
| LOOKAHEAD(2) ( < LT > identifier() < GT > ) #REReference
| ( < LT > < _EOF > < GT > ) #REEOF
};

RULE complex_regular_expression_choices() #REChoice(>1) ::=
  complex_regular_expression() ( < BIT_OR > complex_regular_expression() )*
};

RULE complex_regular_expression() #RESequence(>1) ::=
  ( complex_regular_expression_unit() )+
};

RULE complex_regular_expression_unit() ::=
<? Token t; ?>
(
  StringLiteral() #REStringLiteral
| ( < LT > identifier() < GT > ) #REReference
| character_list()
| t=< LPAREN > complex_regular_expression_choices() < RPAREN >
  (
    < PLUS > #REOneOrMore(1)
  | < STAR > #REZeroOrMore(1)
  | < HOOK > #REZeroOrOne(1)
  | < LBRACE > IntegerLiteral() [ < COMMA >  [ IntegerLiteral() ] ] < RBRACE > #RRepetitionRange(1)
  | {} <? jjtree.closeNodeScope($NODE, 1);
    $BOOL = false;
    if (jjtree.nodeCreated()) {
     jjtreeCloseNodeScope($NODE);
    }?> #REParenthesized(1)
  )
<? ((ASTNode)jjtree.peekNode()).setFirstToken(t); ?>
)
};

RULE character_list() #RECharList ::=
  [ < TILDE > ] < LBRACKET > [ character_descriptor() ( < COMMA > character_descriptor() )* ] < RBRACKET >
};

RULE character_descriptor() #CharDescriptor ::=
  StringLiteral() [ < MINUS > StringLiteral() ]
};

RULE identifier() : Token ::=
  <? Token t; ?>
  t=<IDENTIFIER>
  <? return t; ?>
};

RULE value() : Token ::=
  ( <INTEGER_LITERAL> | <FALSE> | <TRUE> )
  <? return token; ?>
};

/**********************************************
 * THE JJTREE PRODUCTIONS START HERE       *
 **********************************************/

RULE node_descriptor() : ASTNodeDescriptor #NodeDescriptor ::=
<?
    Token t = null;
    String s = null;
?>
  < HASH >
  s=TypeParameter() <? $NODE.setName(s); ?>
  [
   LOOKAHEAD(1)
   < LPAREN >
      [ < GT > <? $NODE.setGreaterThan(); ?> ]
      t=value() <? $NODE.setExpressionText(t.image); ?>
   < RPAREN >
  ]
<?
  jjtree.closeNodeScope($NODE, true);
  $BOOL = false;
  if (jjtree.nodeCreated()) {
   jjtreeCloseNodeScope($NODE);
  }
  return $NODE;
?>
};

/**********************************************
 * THE JAVA GRAMMAR SPECIFICATION STARTS HERE *
 **********************************************/

/*
 * The following production defines Java identifiers - it
 * includes the reserved words of JavaCC also.
 */

RULE TypeParameter() : String ::=
(
  <IDENTIFIER>
| < _LOOKAHEAD >
| < _IGNORE_CASE >
| < _PARSER >
| < _TOKEN >
| < _SPECIAL_TOKEN >
| < _MORE >
| < _SKIP >
| < _EOF >
)
<? return token.image; ?>
};

/*
 * Program structuring syntax follows.
 */
RULE TypeParameters() ::=
  < LT > TypeParameter() ( < COMMA > TypeParameter() )* < GT >
};

RULE FormalParameter() ::=
  Type() TypeParameter()
};


/*
 * Type, name and expression syntax follows.
 */
RULE Type() ::=
   LOOKAHEAD(2) TypeParameter()
 | PrimitiveType()
};

RULE PrimitiveType() ::=
  < BOOLEAN >
| < CHAR >
| < INT >
};


/*
 * Expression syntax follows.
 */
RULE Expression() #Expression ::=
  PrimaryPrefix() ( LOOKAHEAD(2) PrimarySuffix() )*
};

RULE PrimaryPrefix() ::=
  Literal()
| < LPAREN > Expression() < RPAREN >
| TypeParameter()
};

RULE PrimarySuffix() ::=
  < LBRACKET > Expression() < RBRACKET >
| Arguments()
};

RULE Literal() ::=
  < NULL >
| <INTEGER_LITERAL>
| <FLOATING_POINT_LITERAL>
| <CHARACTER_LITERAL>
| <STRING_LITERAL>
| BooleanLiteral()
};

RULE IntegerLiteral() ::= <INTEGER_LITERAL> };

RULE BooleanLiteral() ::= < TRUE > | < FALSE > };

RULE StringLiteral() ::= <STRING_LITERAL> };

/*
 * Parsing this fills "tokens" with all tokens of the arguments
 * excluding the parentheses at each end.
 */
RULE Arguments() ::=
  < LPAREN > [ ArgumentList() ] < RPAREN >
};

RULE ArgumentList() ::=
  Expression() ( < COMMA > Expression() )*
};

/*
 * Statement syntax follows.
 * Parsing this fills "tokens" with all tokens of the block
 * excluding the braces at each end.
 */
RULE Statement() ::=
  < ECODE_DATA > < ECODE_END >
| < LBRACE > ( Statement() )* < RBRACE >
};
