grammar JJTreeParser;

options {
  NODE_MULTI: true,
  NODE_DEFAULT_VOID: true,
  NODE_SCOPE_HOOK: true,
  NODE_CLASS: "ASTNode",
  VISITOR: true,
  VISITOR_DATA_TYPE: "ASTWriter",
  JAVA_PACKAGE: "org.hivevm.cc.parser.jjtree",
  BASE_PARSER: "ASTParser"
}

/************************************************
 * THE JAVACC GRAMMAR SPECIFICATION STARTS HERE *
 ************************************************/
javacc_input() #Grammar =
  (
    < _GRAMMAR > <IDENTIFIER> < SEMICOLON >
    [ < _OPTIONS > < LBRACE > option_binding() (< COMMA > option_binding())* < RBRACE > ]
  ) #CompilationUnit(true)
  (bnf_production()) +
  <EOF>
;

option_binding() #OptionBinding =
  <? var t = getToken(1); ?>
 <IDENTIFIER> < COLON > ( IntegerLiteral() | BooleanLiteral() | StringLiteral() )
  <? setInputOption(t, this.token); ?>
;

bnf_production() #BNF =
<?
	Token t1;
	ASTBNF prod = $NODE;
	ASTNodeDescriptor nd = null;
	JJTNodeScope ns;
	ASTNode eu;
?>
  t1=identifier() [ < LPAREN > FormalParameter() ( < COMMA > FormalParameter() ) * < RPAREN > ]
  [ < COLON > Type() ]
  [ nd=node_descriptor() ]
<?
	prod.setName(t1.image);
	ns = new JJTNodeScope(prod, nd);
?>
  ( <? $NODE.node_scope = ns; ?> ) #BNFDeclaration
  < ASSIGN >
  (
    eu=expansion_choices(prod)
<?
	$NODE.node_scope = ns;
	$NODE.expansion_unit = eu;
?>
  ) #BNFNodeScope
  < RBRACE > < SEMICOLON >
  <? addProduction(prod); ?>
;

expansion_choices(ASTProduction p) : ASTNode #BNFChoice(> 1) =
  expansion(p) ( < BIT_OR > expansion(p) )*
  <? return (ASTNode) jjtree.peekNode(); ?>
;

expansion(ASTProduction p) #BNFSequence(> 1) =
<?
	ASTNode eu;
	ASTNodeDescriptor nd = null;
?>
  ( LOOKAHEAD(1) ( < _LOOKAHEAD > < LPAREN > local_lookahead(p) < RPAREN > ) #BNFLookahead )?
  ( LOOKAHEAD(0, { notTailOfExpansionUnit() } )
    (
      eu=expansion_unit(p)
      [ nd=node_descriptor() ]
<?
	if (jjtree.nodeCreated()) {
		$NODE.node_scope = new JJTNodeScope(p, nd);
		$NODE.expansion_unit = eu;
	}
?>
    ) #BNFExpansionScope(> 1)
  )+
;

local_lookahead(ASTProduction p) =
<?
	boolean commaAtEnd = false;
	boolean emptyLA = true;
?>
  [
    /*
     * The lookahead of 1 is to turn off the warning message that lets
     * us know that an expansion choice can also start with an integer
     * literal because a primary expression can do the same.  But we
     * know that this is what we want.
     */
    LOOKAHEAD(1)
    IntegerLiteral()
    <? emptyLA = false; ?>
  ]
  [ LOOKAHEAD(0, { checkEmptyLA(emptyLA, getToken(1)) } )
    < COMMA > <? commaAtEnd = true; ?>
  ]
  [ LOOKAHEAD(0, { checkEmpty(getToken(1)) } )
    expansion_choices(p)
    <? emptyLA = false; commaAtEnd = false; ?>
  ]
  [ LOOKAHEAD(0, { checkEmptyLAAndCommandEnd(emptyLA, commaAtEnd, getToken(1)) } )
    < COMMA > <? commaAtEnd = true; ?>
  ]
  [ LOOKAHEAD(0, { checkEmptyLAOrCommandEnd(emptyLA, commaAtEnd) } )
    < LBRACE > [ Expression() ] < RBRACE >
  ]
;

expansion_unit(ASTProduction p) : ASTNode =
<? Token t; ?>
(
  LOOKAHEAD(1)
  /*
   * We give this priority over primary expressions which use LOOKAHEAD as the
   * name of its identifier.
   */
  ( < _LOOKAHEAD > < LPAREN > local_lookahead(p) < RPAREN > ) #BNFLookahead
| Statement() #BNFAction
| ( < LBRACKET > expansion_choices(p) < RBRACKET > ) #BNFZeroOrOne
| LOOKAHEAD( identifier() | StringLiteral() | < LT > | Expression() < ASSIGN > )
(
  [
    LOOKAHEAD(Expression() < ASSIGN >)
    Expression() < ASSIGN >
  ]
  (
    regular_expression() [ < DOT > t=<IDENTIFIER>  ]
  | ( identifier() Arguments() ) #BNFNonTerminal
  )
) #BNFAssignment(> 1)
|
  t=< LPAREN > expansion_choices(p) < RPAREN >
  (
    < PLUS > #BNFOneOrMore(1)
  | < STAR > #BNFZeroOrMore(1)
  | < HOOK > #BNFZeroOrOne(1)
  | {} #BNFParenthesized(1)
  )
  <? ((ASTNode) jjtree.peekNode()).setFirstToken(t); ?>
)
<? return (ASTNode) jjtree.peekNode(); ?>
;

regular_expression =
  StringLiteral() #REStringLiteral
|
  LOOKAHEAD(3)
  (
    < LT > [ [ < HASH > ] identifier() < COLON > ] complex_regular_expression_choices() < GT >
  ) #RENamed
| LOOKAHEAD(2) ( < LT > identifier() < GT > ) #REReference
| ( < LT > < _EOF > < GT > ) #REEOF
;

complex_regular_expression_choices() #REChoice(> 1) =
  complex_regular_expression() ( < BIT_OR > complex_regular_expression() )*
;

complex_regular_expression() #RESequence(> 1) =
  ( complex_regular_expression_unit() )+
;

complex_regular_expression_unit =
<?Token t;?>
(
  StringLiteral() #REStringLiteral
| ( < LT > identifier() < GT > ) #REReference
| character_list()
| t=< LPAREN > complex_regular_expression_choices() < RPAREN >
  (
    < PLUS > #REOneOrMore(1)
  | < STAR > #REZeroOrMore(1)
  | < HOOK > #REZeroOrOne(1)
  | < LBRACE > IntegerLiteral() [ < COMMA >  [ IntegerLiteral() ] ] < RBRACE > #RRepetitionRange(1)
  | {} #REParenthesized(1)
  )
<? ((ASTNode) jjtree.peekNode()).setFirstToken(t); ?>
)
;

character_list() #RECharList =
  [ < TILDE > ] < LBRACKET > [ character_descriptor() ( < COMMA > character_descriptor() )* ] < RBRACKET >
;

character_descriptor() #CharDescriptor =
  StringLiteral() [ < MINUS > StringLiteral() ]
;

identifier() : Token =
  <? Token t; ?>
  t=<IDENTIFIER>
  <? return t; ?>
;

value() : Token =
  ( <INTEGER_LITERAL> | <FALSE> | <TRUE> )
  <? return token; ?>
;

/**********************************************
 * THE JJTREE PRODUCTIONS START HERE       *
 **********************************************/

node_descriptor() : ASTNodeDescriptor #NodeDescriptor =
<?
	Token t = null;
	String s = null;
?>
  < HASH >
  s=TypeParameter() <? $NODE.setName(s); ?>
  [
   LOOKAHEAD(1)
   < LPAREN >
      [ < GT > <? $NODE.setGreaterThan(); ?> ]
      t=value() <? $NODE.setExpressionText(t.image); ?>
   < RPAREN >
  ]
<?
	return $NODE;
?>
;

/**********************************************
 * THE JAVA GRAMMAR SPECIFICATION STARTS HERE *
 **********************************************/

/*
 * The following production defines Java identifiers - it
 * includes the reserved words of JavaCC also.
 */

TypeParameter() : String =
(
  <IDENTIFIER>
| < _LOOKAHEAD >
| < _IGNORE_CASE >
| < _GRAMMAR >
| < _OPTIONS >
| < _TOKEN >
| < _SPECIAL_TOKEN >
| < _MORE >
| < _SKIP >
| < _EOF >
)
<? return token.image; ?>
;

/*
 * Program structuring syntax follows.
 */
TypeParameters =
  < LT > TypeParameter() ( < COMMA > TypeParameter() )* < GT >
;

FormalParameter =
  Type() TypeParameter()
;


/*
 * Type, name and expression syntax follows.
 */
Type =
   LOOKAHEAD(2) TypeParameter()
 | PrimitiveType()
;

PrimitiveType =
  < BOOLEAN >
| < CHAR >
| < INT >
;


/*
 * Expression syntax follows.
 */
Expression() #Expression =
  PrimaryPrefix() ( LOOKAHEAD(2) PrimarySuffix() )*
;

PrimaryPrefix =
  Literal()
| < LPAREN > Expression() < RPAREN >
| TypeParameter()
;

PrimarySuffix =
  < LBRACKET > Expression() < RBRACKET >
| Arguments()
;

Literal =
  < NULL >
| <INTEGER_LITERAL>
| <FLOATING_POINT_LITERAL>
| <CHARACTER_LITERAL>
| <STRING_LITERAL>
| BooleanLiteral()
;

IntegerLiteral = <INTEGER_LITERAL> ;

BooleanLiteral = < TRUE > | < FALSE > ;

StringLiteral = <STRING_LITERAL> ;

/*
 * Parsing this fills "tokens" with all tokens of the arguments
 * excluding the parentheses at each end.
 */
Arguments =
  < LPAREN > [ ArgumentList() ] < RPAREN >
;

ArgumentList =
  Expression() ( < COMMA > Expression() )*
;

/*
 * Statement syntax follows.
 * Parsing this fills "tokens" with all tokens of the block
 * excluding the braces at each end.
 */
Statement =
  < ECODE_DATA > < ECODE_END >
| < LBRACE > ( Statement() )* < RBRACE >
;
