package __JAVA_PACKAGE__;

/**
 * Token literal values and constants. Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

    // End of File
    int EOF = 0;

    // RegularExpression Ids
//@foreach(TOKENS)
    int __TOKENS_LABEL__ = __TOKENS_ORDINAL__;
//@end

    // Lexical states
//@foreach(STATES)
    int __STATES_NAME__ = __STATES_INDEX__;
//@end

    // Literal token values
    String[] tokenImage = {
        "<EOF>",
//@foreach(PRODUCTIONS)
        __PRODUCTIONS_LABEL__
//@end
    };
}
