// Copyright 2024 HiveVM.ORG. All rights reserved.
// Copyright (c) 2006, Sun Microsystems, Inc. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Derived from JavaCC 7.0.12: src/main/resources/templates/cpp/TokenManager.h.template, src/main/resources/templates/TokenManager.template

// disable warnings on parser header files
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-parameter"
#pragma GCC diagnostic ignored "-Wunused-variable"

#ifndef WAGGLE_TOKEN_MANAGER
#define WAGGLE_TOKEN_MANAGER

#include <iostream>
#include "Waggle.h"
#include "Token.h"
#include "TokenManagerErrorHandler.h"

//@if(CPP_NAMESPACE)
namespace __CPP_NAMESPACE__ {
//@fi

/**
 * An implementation for this interface is generated by JavaCCParser.
 * The user is free to use any implementation of their choice.
 */

class TokenManager {
public:
	TokenManager() {
//@if(DEBUG_TOKEN_MANAGER)
		trace = true;
//@else
		trace = false;
//@fi
	}
	virtual ~TokenManager() {}

	// This gets the next token from the input stream. A token of kind 0 (<EOF>) should be returned on EOF.
	virtual Token * getNextToken() = 0;
	virtual void lexicalError() = 0;
protected:
	bool                       trace;
public:
	void enable_tracing() {
//@if(DEBUG_TOKEN_MANAGER)
		trace = true;
//@fi
	}
	void disable_tracing(){
//@if(DEBUG_TOKEN_MANAGER)
		trace = false; 
//@fi
	}
	bool trace_enabled() const { return trace; }
};

//@if(CPP_NAMESPACE)
}
//@fi

#endif

#pragma GCC diagnostic pop