// Copyright 2024 HiveVM.ORG. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause

package org.hivevm.cc;


import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.nio.file.Files;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.hivevm.cc.generator.GeneratorProvider;
import org.hivevm.cc.generator.TreeContext;
import org.hivevm.cc.jjtree.ASTWriter;
import org.hivevm.cc.jjtree.JJTreeParserDefault;
import org.hivevm.cc.parser.JavaCCData;
import org.hivevm.cc.parser.JavaCCErrors;
import org.hivevm.cc.parser.JavaCCParserDefault;
import org.hivevm.cc.parser.StringProvider;
import org.hivevm.cc.semantic.Semanticize;

/**
 * The {@link Parser} class.
 */
public class Parser {

    private static final Pattern GENERATED = Pattern.compile("@generated\\(([^)]+)\\)");

    private final File file;

    private final Language     language;
    private final File         targetDir;
    private final List<String> customNodes;

    public Parser(File file, Language language, File targetDir, List<String> customNodes) {
        this.file = file;
        this.language = language;
        this.targetDir = targetDir;
        this.customNodes = customNodes;
    }

    /**
     * Run the parser generator.
     */
    public final void parse() {
        var arguments = new ArrayList<String>();
        arguments.add("-CODE_GENERATOR=" + this.language.name());
        arguments.add("-OUTPUT_DIRECTORY=" + this.targetDir.getAbsolutePath());

        var filename = this.file.getName();
        var lexerFile = new File(this.file.getParentFile(),
            filename.substring(0, filename.lastIndexOf('.')) + ".lex"
        );

        try {
            var text = "";
            if (filename.endsWith(".jjt")) {
                if ((this.customNodes != null) && !this.customNodes.isEmpty()) {
                    arguments.add("-NODE_CUSTOM=" + String.join(",", this.customNodes));
                }

                Parser.bannerLine("Tree Builder");
                JavaCCErrors.reInit();
                System.out.printf("Reading from file '%s' ...\n", file);

                var options = parseContext(arguments);
                Parser.createOutputDir(options.getOutputDirectory());

                text = new String(Files.readAllBytes(file.toPath()));
                if (Parser.isGenerated(text)) {
                    System.out.printf("%s was generated by jjtree.  Cannot run jjtree again.\n", file);
                    System.exit(1);
                }

                var parser = new JJTreeParserDefault(text, options);
                var grammar = parser.parse();
                if (Boolean.getBoolean("jjtree-dump")) {
                    grammar.dump(" ");
                }

                var buffer = new StringWriter();
                var generator = GeneratorProvider.generatorFor(options.getOutputLanguage());
                try (var writer = new ASTWriter(buffer, options.getOutputLanguage())) {
                    Parser.writeGenerated(writer);
                    generator.generateAST(grammar, writer, options);
                } catch (IOException ioe) {
                    System.out.println("Error setting input: " + ioe.getMessage());
                    System.exit(1);
                }

                text = buffer.toString();
                System.out.println("Annotated grammar generated successfully!");

                var jj = options.getOutputFile().isEmpty()
                    ? filename.substring(0, filename.length() - 1)
                    : options.getOutputFile();
                try (var writer = new FileWriter(new File(options.getOutputDirectory(), jj))) {
                    writer.write(text);
                }
            } else {
                text = new String(Files.readAllBytes(file.toPath()));
            }

            if (lexerFile.exists()) {
                System.out.printf("Reading from file %s ...\n", file);
                text += new String(Files.readAllBytes(lexerFile.toPath()));
            }

            Parser.bannerLine("Parser Generator");
            JavaCCErrors.reInit();

            var options = parseContext(arguments);
            var request = new JavaCCData(Parser.isGenerated(text), options);
            var parser = new JavaCCParserDefault(new StringProvider(text), options);
            parser.initialize(request);
            parser.javacc_input();

            // Initialize the parser data
            Parser.createOutputDir(options.getOutputDirectory());
            Semanticize.semanticize(request, options);
            options.setParser(request.getParserName());
            var generator = GeneratorProvider.generatorFor(options.getOutputLanguage());
            generator.generate(request);
        } catch (ParseException | IOException e) {
            e.printStackTrace();
        }

        if (JavaCCErrors.hasError()) {
            System.out.printf("Detected %s errors and %s warnings.\n",
                JavaCCErrors.get_error_count(), JavaCCErrors.get_warning_count());
            System.exit(JavaCCErrors.get_error_count() == 0 ? 0 : 1);
        }
        else if (JavaCCErrors.hasWarning()) {
            System.out.printf("Parser generated with 0 errors and %s warnings.\n",
                JavaCCErrors.get_warning_count());
        }
        else {
            System.out.println("Parser generated successfully.");
        }
    }

    /**
     * Writes the generated string.
     */
    private static void writeGenerated(PrintWriter writer) {
        writer.println("/* @generated(JJTree) */");
    }

    /**
     * Parses the tool list from the generated string.
     */
    private static List<String> readToolNameList(String text) {
        Matcher matcher = Parser.GENERATED.matcher(text);
        if (matcher.find())
            return Arrays.asList(matcher.group(1).split(","));
        return Collections.emptyList();
    }

    /**
     * Returns true if tool name passed is one of the tool names returned by
     * getToolNames(fileName).
     */
    private static boolean isGenerated(String data) {
        for (var element : Parser.readToolNameList(data)) {
            if ("JJTree".equals(element)) {
                return true;
            }
        }
        return false;
    }

    private static TreeContext parseContext(List<String> args) {
        var options = new TreeContext();
        for (var arg : args) {
            if (!options.isOption(arg)) {
                System.out.printf("Argument '%s' must be an option setting.\n", arg);
                System.exit(1);
            }
            options.setCmdLineOption(arg);
        }
        options.validate();
        return options;
    }

    private static void createOutputDir(File outputDir) {
        if (!outputDir.exists()) {
            JavaCCErrors.warning(
                "Output directory \"" + outputDir + "\" does not exist. Creating the directory.");

            if (!outputDir.mkdirs()) {
                JavaCCErrors.semantic_error("Cannot create the output directory : " + outputDir);
                return;
            }
        }

        if (!outputDir.isDirectory()) {
            JavaCCErrors.semantic_error("\"" + outputDir + " is not a valid output directory.");
            return;
        }

        if (!outputDir.canWrite()) {
            JavaCCErrors.semantic_error(
                "Cannot write to the output output directory : \"" + outputDir + "\"");
        }
    }    /**
     * This prints the banner line when the various tools are invoked. This takes as argument the
     * tool's full name and its version.
     */
    public static void bannerLine(String fullName) {
        System.out.printf("Java Compiler Compiler Version %s (%s)\n",
            HiveCCVersion.VERSION.toString(), fullName);
    }
}
