// Copyright 2024 HiveVM.ORG. All rights reserved.
// Copyright (c) 2006, Sun Microsystems, Inc. All rights reserved.
// SPDX-License-Identifier: BSD-3-Clause
//
// Derived from JavaCC 7.0.12: test/javaFileGeneration/expected/non-static/ParserConstants.java, test/javaFileGeneration/expected/static/ParserConstants.java

//@if(JAVA_PACKAGE)
package __JAVA_PACKAGE__;
//@fi

/**
 * Token literal values and constants. Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

	// End of File
	int EOF = 0;

	// RegularExpression Ids
//@foreach(TOKENS)
	int __TOKENS_LABEL__ = __TOKENS_ORDINAL__;
//@end

	// Lexical states
//@foreach(STATES)
	int __STATES_NAME__ = __STATES_INDEX__;
//@end

	// Literal token values
	String[] tokenImage = {
//@foreach(REXPRESSION_COUNT)
			__REXPRESSION_LABEL__
//@end
	};
}
